# ------ dataset_path ------
data_path: '/mnt/mlc1/liujunyuan/dataset/caltech-101/'
root_path: '/mnt/mlc1/liujunyuan/dataset/'

init_Zeta: 0.1
init_epsilon: 7
init_beta: 4.5
# ------ Hyperparamters ------

#load_cache: Ture
#load_pre_feat: Ture
load_cache: False
load_pre_feat: False

# ------ Basic Config ------
dataset: 'caltech101'


lr: 0.001
train_epoch: 100
batch_size: 64

# only 100 categories in the file 'split_zhou_Caltech101.json'
num_classes: 100

num_threads: 8
save_interval: 50

cache_dir: './model/clip'
search_hp: True

#search_scale: [10,1, 20]
search_scale: [10,1, 50]


gpt3_prompt_file: './gpt_file/caltech_prompt.json'
gpt3_prompt : Ture
# ------ Dalle Dataset -----
dalle_dataset: 'dalle_caltech'
dalle_shots: [8,4,2,4,2]