# ------ dataset_path ------
data_path: '/tmp/yh_maple/data/imagenet/'
root_path: '/tmp/yh_maple/data/'

# ------ Hyperparamters ------
alpha: 0.5

init_beta: 1
init_Zeta: 1
init_epsilon: 3

#load_cache: Ture
load_pre_feat: Ture

load_cache: False
#load_pre_feat: False

search_hp: True
# ------ Basic Config ------
dataset: 'imagenet'


search_scale: [15,20, 50]

lr: 0.001
train_epoch: 20
batch_size: 256

num_classes: 1000

num_threads: 8
save_interval: 100

cache_dir: './model/clip'
augment_epoch: 10

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_imagenet'
dalle_shots: [8,3,2,1,8]

gpt3_prompt_file: './gpt_file/imagenet_prompt.json'
gpt3_prompt : Ture