# ------ dataset_path ------

data_path: '/mnt/mlc1/liujunyuan/dataset/oxford_pets/'
root_path: '/mnt/mlc1/liujunyuan/dataset/'

init_Zeta: 0.4
init_epsilon: 1.7
init_beta: 0.2
# ------ Hyperparamters ------
alpha: 0.3

search_scale: [15,1, 50]


load_cache: False
load_pre_feat: False

search_hp: True

# ------ Basic Config ------
dataset: 'oxford_pets'

lr: 0.001
train_epoch: 20
batch_size: 64

num_classes: 37

num_threads: 8
save_interval: 50

cache_dir: './model/clip'

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_pets'
dalle_shots: [6,3,7,4,8]

gpt3_prompt_file: './gpt_file/oxford_pets_prompt.json'
gpt3_prompt : Ture
