# ------ dataset_path ------
data_path: '/mnt/mlc1/liujunyuan/dataset/ucf101/'
root_path: '/mnt/mlc1/liujunyuan/dataset/'

init_Zeta: 1
init_epsilon: 1.5
init_beta: 1
# ------ Hyperparamters ------
alpha: 0.5


load_cache: False
load_pre_feat: False

search_scale: [15,1, 50]

search_hp: True


# ------ Basic Config ------
dataset: 'ucf101'


lr: 0.001
train_epoch: 100
batch_size: 64

num_classes: 101

num_threads: 8
save_interval: 50

cache_dir: './model/clip'

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_ucf'
dalle_shots: [1,4,9,1,1]

gpt3_prompt_file: './gpt_file/ucf101_prompt.json'
gpt3_prompt : Ture

